<a href="https://colab.research.google.com/github/ManKyCoNguyet/DeepLearning_personalRepository/blob/main/Tuan01/lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
1
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [ ]:
#2
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)


tensor([[0.0241, 0.9056, 0.9626, 0.5320],
        [0.8198, 0.6146, 0.1990, 0.7782],
        [0.2216, 0.7436, 0.0862, 0.8251]])
tensor([[-0.9388,  0.0950, -0.8639,  0.6722],
        [-0.4275, -0.1722, -0.7153,  0.4474],
        [-0.1828, -1.0948,  0.6594,  0.3066]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [ ]:
f = torch.full((5, 5), 10)
print(f)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


In [ ]:
#3
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


In [ ]:
#4
import torch

a = torch.randn(3, 4, 5)

print("Original tensor:")
print(a)

print("\nTensor a[1]:")
print(a[1])

print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[ 1.1812,  1.8426, -0.7693,  0.2737,  0.4714],
         [-1.4508,  0.1230,  0.7278,  2.0103,  0.3140],
         [-0.7252, -1.3314,  1.3450,  0.3302, -1.0108],
         [ 0.8323,  0.0068,  0.1349, -0.7699,  0.6175]],

        [[-2.0200,  0.7681,  0.6623,  0.1199, -0.3632],
         [-0.8806, -1.0605, -0.8795, -0.1462, -0.3070],
         [-2.1222, -0.0292,  0.1105, -0.0883, -0.1349],
         [-0.0415,  0.9482, -0.4848, -0.7332, -0.6175]],

        [[ 0.4146,  0.6003, -0.0553, -0.9073,  0.1600],
         [ 1.4872, -0.7310, -0.9452,  0.2710,  0.4656],
         [ 0.6434,  1.0129,  0.2756,  1.5524, -0.3474],
         [-0.4162,  0.0110, -0.8204,  0.6122,  0.4531]]])

Tensor a[1]:
tensor([[-2.0200,  0.7681,  0.6623,  0.1199, -0.3632],
        [-0.8806, -1.0605, -0.8795, -0.1462, -0.3070],
        [-2.1222, -0.0292,  0.1105, -0.0883, -0.1349],
        [-0.0415,  0.9482, -0.4848, -0.7332, -0.6175]])

Tensor a[1:, 2:4]:
tensor([[[-2.1222, -0.0292,  0.1105, -0.0883, -0.1

In [ ]:
print(a[1].shape)
print(a[1:, 2:4].shape)
print("\nTensor a[:, :, -2:]:")
print(a[:, :, -2:])

torch.Size([4, 5])
torch.Size([2, 2, 5])

Tensor a[:, :, -2:]:
tensor([[[ 0.2737,  0.4714],
         [ 2.0103,  0.3140],
         [ 0.3302, -1.0108],
         [-0.7699,  0.6175]],

        [[ 0.1199, -0.3632],
         [-0.1462, -0.3070],
         [-0.0883, -0.1349],
         [-0.7332, -0.6175]],

        [[-0.9073,  0.1600],
         [ 0.2710,  0.4656],
         [ 1.5524, -0.3474],
         [ 0.6122,  0.4531]]])


In [ ]:
#5
import torch

a = torch.randn(3, 4)

print("Original:")
print(a)

print("\nFlatten:")
print(a.ravel())

print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[-1.3862, -0.7009, -1.5544, -1.9575],
        [-1.2834, -1.4325,  1.2086, -0.9263],
        [-0.3027, -0.6351, -0.4902, -1.9271]])

Flatten:
tensor([-1.3862, -0.7009, -1.5544, -1.9575, -1.2834, -1.4325,  1.2086, -0.9263,
        -0.3027, -0.6351, -0.4902, -1.9271])

Reshape to 3 x 2 x 2:
tensor([[[-1.3862, -0.7009],
         [-1.5544, -1.9575]],

        [[-1.2834, -1.4325],
         [ 1.2086, -0.9263]],

        [[-0.3027, -0.6351],
         [-0.4902, -1.9271]]])


In [ ]:
print(a.reshape(2, 6))

tensor([[-1.3862, -0.7009, -1.5544, -1.9575, -1.2834, -1.4325],
        [ 1.2086, -0.9263, -0.3027, -0.6351, -0.4902, -1.9271]])


In [ ]:
#6
import torch

a = torch.randn(2, 3)
b = torch.randn(2, 3)

print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)

print("\na / b:")
print(a / b)

print("\na^2:")
print(a ** 2)

print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[-0.3908,  0.5930,  1.3068],
        [-2.2075,  0.4587,  0.7916]])
b:
tensor([[ 0.5867, -0.4220,  0.1610],
        [-0.4139,  2.1165,  0.1124]])

a + b:
tensor([[ 0.1959,  0.1710,  1.4679],
        [-2.6213,  2.5753,  0.9040]])

a / b:
tensor([[-0.6661, -1.4052,  8.1158],
        [ 5.3338,  0.2167,  7.0398]])

a^2:
tensor([[0.1527, 0.3517, 1.7078],
        [4.8728, 0.2104, 0.6266]])

Matrix multiplication:
tensor([[-0.2692,  1.5639],
        [-1.3613,  1.9735]])


In [ ]:
#7
import torch

a = torch.randn(3, 4)

print(a)
print("\nMean:")
print(torch.mean(a, dim=0))

print("\nStandard deviation:")
print(torch.std(a, dim=0))

print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[ 0.9389,  1.1899,  0.2914, -0.5164],
        [ 0.7951,  0.2082,  1.0819, -1.2043],
        [-1.1480, -0.4576,  1.7443, -0.6342]])

Mean:
tensor([ 0.1954,  0.3135,  1.0392, -0.7850])

Standard deviation:
tensor([1.1656, 0.8288, 0.7274, 0.3679])

Cumulative sum:
tensor([[ 0.9389,  1.1899,  0.2914, -0.5164],
        [ 1.7341,  1.3981,  1.3733, -1.7207],
        [ 0.5861,  0.9405,  3.1177, -2.3549]])


In [ ]:
print(a)
print("\nMean:")
print(torch.mean(a, dim=1))

print("\nStandard deviation:")
print(torch.std(a, dim=1))

print("\nCumulative sum:")
print(torch.cumsum(a, dim=1))

tensor([[ 0.9389,  1.1899,  0.2914, -0.5164],
        [ 0.7951,  0.2082,  1.0819, -1.2043],
        [-1.1480, -0.4576,  1.7443, -0.6342]])

Mean:
tensor([ 0.4760,  0.2202, -0.1239])

Standard deviation:
tensor([0.7622, 1.0169, 1.2794])

Cumulative sum:
tensor([[ 0.9389,  2.1289,  2.4203,  1.9039],
        [ 0.7951,  1.0033,  2.0852,  0.8809],
        [-1.1480, -1.6057,  0.1387, -0.4955]])


In [ ]:
#8
import torch

x = torch.tensor(
    3.6,
    requires_grad=True
)

y = x * x

y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


In [ ]:
import torch

x = torch.tensor(
    3.6,
    requires_grad=True
)

y =  3*x**2 + 2*x + 1

y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(23.6000)


In [ ]:
#9
import numpy as np
import torch

polynomial = np.poly1d([1, 2, 3])
N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[0.8818],
        [0.9946],
        [0.6191]], requires_grad=True)
Learned coefficients:
tensor([[1.0002],
        [2.0000],
        [2.9891]], requires_grad=True)


In [ ]:
#10
import random
import torch

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2

    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4

    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.0859, requires_grad=True)
B = tensor(4.9141, requires_grad=True)
C = tensor(3.9141, requires_grad=True)
D = tensor(2.9141, requires_grad=True)


In [ ]:
#11
#Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.
import torch

# Tạo Tensor X có 24 phần tử
X = torch.arange(24)
print("Tensor X ban đầu:\n", X)

# Reshape lần lượt thành 4x6, 2x12 và 2x3x4
X_4x6 = X.reshape(4, 6)
print("\nReshape thành 4x6:\n", X_4x6)

X_2x12 = X.reshape(2, 12)
print("\nReshape thành 2x12:\n", X_2x12)

X_2x3x4 = X.reshape(2, 3, 4)
print("\nReshape thành 2x3x4:\n", X_2x3x4)

Tensor X ban đầu:
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

Reshape thành 4x6:
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

Reshape thành 2x12:
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

Reshape thành 2x3x4:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [ ]:
#Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.
# Tạo hai Tensor A, B kích thước 3x4 (ngẫu nhiên)
A = torch.randn(3, 4)
B = torch.randn(3, 4)

print("Tensor A:\n", A)
print("Tensor B:\n", B)

# Các phép toán cơ bản
print("\nA + B:\n", A + B)
print("\nA * B:\n", A * B)
print("\nA / B:\n", A / B)

# Thống kê (trung bình và độ lệch chuẩn theo cột với dim=0)
print("\nTrung bình theo cột (dim=0):\n", torch.mean(A, dim=0))
print("\nĐộ lệch chuẩn theo cột (dim=0):\n", torch.std(A, dim=0))

Tensor A:
 tensor([[ 2.3996, -0.5255,  0.8947,  1.8948],
        [-0.4533, -0.5274,  1.9793, -1.4567],
        [ 1.6098, -0.6078, -1.3878,  0.9921]])
Tensor B:
 tensor([[-1.1139, -0.4340, -0.9279, -0.1060],
        [-0.2059,  0.6156,  0.1152,  0.1394],
        [ 0.0888,  0.4956,  1.6091, -0.3700]])

A + B:
 tensor([[ 1.2857, -0.9595, -0.0331,  1.7888],
        [-0.6592,  0.0882,  2.0945, -1.3173],
        [ 1.6987, -0.1121,  0.2213,  0.6221]])

A * B:
 tensor([[-2.6729,  0.2281, -0.8302, -0.2009],
        [ 0.0933, -0.3247,  0.2279, -0.2031],
        [ 0.1430, -0.3012, -2.2330, -0.3670]])

A / B:
 tensor([[ -2.1542,   1.2109,  -0.9643, -17.8701],
        [  2.2019,  -0.8568,  17.1868, -10.4484],
        [ 18.1263,  -1.2262,  -0.8625,  -2.6816]])

Trung bình theo cột (dim=0):
 tensor([ 1.1854, -0.5536,  0.4954,  0.4767])

Độ lệch chuẩn theo cột (dim=0):
 tensor([1.4731, 0.0469, 1.7187, 1.7342])


In [ ]:
#Cho y = 2x² + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.
# Khởi tạo biến x = 2 với requires_grad=True để tính đạo hàm
x = torch.tensor(2.0, requires_grad=True)

# Khai báo hàm số y
y = 2 * (x ** 2) + 5 * x + 3

# Gọi backward để tự động tính gradient
y.backward()

print("Giá trị đạo hàm tự động (dy/dx) tại x = 2 là:", x.grad)

Giá trị đạo hàm tự động (dy/dx) tại x = 2 là: tensor(13.)


In [ ]:
#Thay đa thức trong Bài 9 bằng y = 2x² - 3x + 5; huấn luyện và cho biết các hệ số tìm được.
import numpy as np
import torch

polynomial = np.poly1d([2, -3, 5])
N = 50

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.05)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-0.0094],
        [ 0.8541],
        [ 0.4140]], requires_grad=True)
Learned coefficients:
tensor([[ 2.0012],
        [-3.0002],
        [ 4.9320]], requires_grad=True)
